name: "Probabilistic-Numerics.org"
url: http://www.probabilistic-numerics.org/test
baseurl: http://www.probabilistic-numerics.org/test
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
description: A community website collecting research on algorithms that assign probability distributions to the unknown result of deterministic computations.

navigation:
<<<<<<< HEAD
- text: News
  url: /index.html
- text: Blog
  url: /blog/index.html
=======
- text: About
  url: /index.html
- text: News/Blog
  url: /news/index.html
- text: Research
  url: /research/index.html
>>>>>>> 972df94d7146ea2cf75e273249ba0b64dc2eb56f
- text: Meetings
  url: /meetings/index.html
- text: Research Areas
  url: /research/index.html
- text: Literature
  url: /literature/index.html

ftp_host: 'ud02.udmedia.de'
ftp_dir: '/html/numerics/test/'
ftp_passive: false

markdown: kramdown

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography

