name: "Probabilistic-Numerics.org"
# url: http://www.probabilistic-numerics.org
# baseurl: http://www.probabilistic-numerics.org
permalink: /:year/:month/:day/:title
timezone: Europe/Berlin
description: A community website collecting research on algorithms that assign probability distributions to the unknown result of deterministic computations.

navigation:
- text: About/News
  url: /index.html
- text: Research Areas
  url: /research/index.html
- text: Literature
  url: /literature/index.html

markdown: kramdown

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography

