name: "Jan-Willem van de Meent @ robots.ox.ac.uk"
# url: http://www.robots.ox.ac.uk
# baseurl: http://www.robots.ox.ac.uk/~jwvdm
permalink: /:year/:month/:day/:title
timezone: Europe/London

navigation:
- text: About/News
  url: /index.html
- text: Research Areas
  url: /research/index.html
- text: Literature
  url: /literature/index.html

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography
